// Code generated by Kitex v0.12.1. DO NOT EDIT.
package orderservice

import (
	server "github.com/cloudwego/kitex/server"
	order_service "order/rpc/order/kitex_gen/demo/order_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler order_service.OrderService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler order_service.OrderService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
