

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - /usr/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=orderdb
      - MYSQL_USER=order
      - MYSQL_PASSWORD=123456
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /usr/redis/data:/data
  etcd:
    image: bitnami/etcd:latest
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - /usr/etcd/data:/bitnami/etcd-data
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379

  rpc:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - etcd
    environment:
      - ETCD_HOST=etcd:2379
    volumes:
      - /usr/src/order/log:/usr/src/app/log
