// Code generated by hertz generator.

package order

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateorderaddressMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateorderstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserordersMw() []app.HandlerFunc {
	// your code...
	return nil
}
