// Code generated by hertz generator.

package payment

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelpaymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _processpaymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handlepaymenttimeoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateorderstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorderbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}
