// Code generated by hertz generator.

package user

import (
	"context"
	"github.com/MelodyDeep/TikTok-E-commerce/app/hertz/biz/service"
	"github.com/MelodyDeep/TikTok-E-commerce/app/hertz/biz/utils"
	"github.com/MelodyDeep/TikTok-E-commerce/app/hertz/hertz_gen/user"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"log"
)

// Register .
// @router /register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		log.Printf("Failed to bind and validate request: %v", err)
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := &user.RegisterResp{}
	resp, err = service.NewRegisterService(ctx, c).Run(&req)
	if err != nil {
		utils.SendErrResponse(ctx, c, consts.StatusOK, err)
		return
	}
	c.JSON(consts.StatusOK, resp)

}

// Login .
// @router /login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		log.Printf("Failed to bind and validate request: %v", err)
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := &user.LoginResp{}
	resp, err = service.NewLoginService(ctx, c).Run(&req)
	if err != nil {
		utils.SendErrResponse(ctx, c, consts.StatusOK, err)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// Logout .
// @router /logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LogoutReq
	err = c.BindAndValidate(&req)
	if err != nil {
		log.Printf("Failed to bind and validate request: %v", err)
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := &user.LogoutResp{}
	resp, err = service.NewLogoutService(ctx, c).Run(&req)
	if err != nil {
		utils.SendErrResponse(ctx, c, consts.StatusOK, err)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// DeleteUser .
// @router /deleteuser [POST]
func DeleteUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.DeleteUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		log.Printf("Failed to bind and validate request: %v", err)
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := &user.DeleteUserResp{}
	resp, err = service.NewDeleteUserService(ctx, c).Run(&req)
	if err != nil {
		utils.SendErrResponse(ctx, c, consts.StatusOK, err)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// UpdateUser .
// @router /updateuser [POST]
func UpdateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UpdateUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := &user.UpdateUserResp{}
	resp, err = service.NewUpdateUserService(ctx, c).Run(&req)
	if err != nil {
		utils.SendErrResponse(ctx, c, consts.StatusOK, err)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// GetUser .
// @router /getuser [GET]
func GetUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := &user.GetUserResp{}
	resp, err = service.NewGetUserService(ctx, c).Run(&req)
	if err != nil {
		utils.SendErrResponse(ctx, c, consts.StatusOK, err)
		return
	}
	c.JSON(consts.StatusOK, resp)
}
