// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	payment "github.com/MelodyDeep/TikTok-E-commerce/app/hertz/biz/router/payment"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	payment.Register(r)
}
