// Code generated by Kitex v0.12.1. DO NOT EDIT.

package orderservice

import (
	orderservice2 "TikTok-E-commerce-payment/kitex_gen/orderservice"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateOrder(ctx context.Context, Req *CreateOrderRequest, callOptions ...callopt.Option) (r *CreateOrderResponse, err error)
	GetOrderByID(ctx context.Context, Req *GetOrderRequest, callOptions ...callopt.Option) (r *GetOrderResponse, err error)
	UpdateOrderStatus(ctx context.Context, Req *UpdateOrderStatusRequest, callOptions ...callopt.Option) (r *UpdateOrderStatusResponse, err error)
	DeleteOrder(ctx context.Context, Req *DeleteOrderRequest, callOptions ...callopt.Option) (r *DeleteOrderResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(orderservice2.serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderServiceClient{
		kClient: orderservice2.newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderServiceClient struct {
	*orderservice2.kClient
}

func (p *kOrderServiceClient) CreateOrder(ctx context.Context, Req *CreateOrderRequest, callOptions ...callopt.Option) (r *CreateOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrder(ctx, Req)
}

func (p *kOrderServiceClient) GetOrderByID(ctx context.Context, Req *GetOrderRequest, callOptions ...callopt.Option) (r *GetOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrderByID(ctx, Req)
}

func (p *kOrderServiceClient) UpdateOrderStatus(ctx context.Context, Req *UpdateOrderStatusRequest, callOptions ...callopt.Option) (r *UpdateOrderStatusResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateOrderStatus(ctx, Req)
}

func (p *kOrderServiceClient) DeleteOrder(ctx context.Context, Req *DeleteOrderRequest, callOptions ...callopt.Option) (r *DeleteOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteOrder(ctx, Req)
}
