// Code generated by Kitex v0.12.1. DO NOT EDIT.
package orderservice

import (
	orderservice2 "TikTok-E-commerce-payment/kitex_gen/orderservice"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler OrderService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(orderservice2.serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler OrderService, opts ...server.RegisterOption) error {
	return svr.RegisterService(orderservice2.serviceInfo(), handler, opts...)
}
