// Code generated by Kitex v0.9.1. DO NOT EDIT.

package orderservice

import (
	"context"
	order_service "github.com/MelodyDeep/TikTok-E-commerce/rpc_gen/kitex_gen/order_service"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateOrder(ctx context.Context, Req *order_service.CreateOrderRequest, callOptions ...callopt.Option) (r *order_service.BaseResponse, err error)
	QueryOrderById(ctx context.Context, Req *order_service.QueryOrderByIdRequest, callOptions ...callopt.Option) (r *order_service.QueryOrderResponse, err error)
	QueryOrdersByUserId(ctx context.Context, Req *order_service.QueryOrdersByUserIdRequest, callOptions ...callopt.Option) (r *order_service.QueryOrdersResponse, err error)
	UpdateOrder(ctx context.Context, Req *order_service.UpdateOrderRequest, callOptions ...callopt.Option) (r *order_service.BaseResponse, err error)
	UpdateOrderStatus(ctx context.Context, Req *order_service.UpdateOrderStatusRequest, callOptions ...callopt.Option) (r *order_service.BaseResponse, err error)
	UpdateOrderAddresseeInfo(ctx context.Context, Req *order_service.UpdateOrderAddresseeInfoRequest, callOptions ...callopt.Option) (r *order_service.BaseResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderServiceClient struct {
	*kClient
}

func (p *kOrderServiceClient) CreateOrder(ctx context.Context, Req *order_service.CreateOrderRequest, callOptions ...callopt.Option) (r *order_service.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrder(ctx, Req)
}

func (p *kOrderServiceClient) QueryOrderById(ctx context.Context, Req *order_service.QueryOrderByIdRequest, callOptions ...callopt.Option) (r *order_service.QueryOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryOrderById(ctx, Req)
}

func (p *kOrderServiceClient) QueryOrdersByUserId(ctx context.Context, Req *order_service.QueryOrdersByUserIdRequest, callOptions ...callopt.Option) (r *order_service.QueryOrdersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryOrdersByUserId(ctx, Req)
}

func (p *kOrderServiceClient) UpdateOrder(ctx context.Context, Req *order_service.UpdateOrderRequest, callOptions ...callopt.Option) (r *order_service.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateOrder(ctx, Req)
}

func (p *kOrderServiceClient) UpdateOrderStatus(ctx context.Context, Req *order_service.UpdateOrderStatusRequest, callOptions ...callopt.Option) (r *order_service.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateOrderStatus(ctx, Req)
}

func (p *kOrderServiceClient) UpdateOrderAddresseeInfo(ctx context.Context, Req *order_service.UpdateOrderAddresseeInfoRequest, callOptions ...callopt.Option) (r *order_service.BaseResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateOrderAddresseeInfo(ctx, Req)
}
