// Code generated by Kitex v0.9.1. DO NOT EDIT.

package paymentservice

import (
	"context"
	"errors"
	payment "github.com/MelodyDeep/TikTok-E-commerce/rpc_gen/kitex_gen/rpc/payment"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ProcessPayment": kitex.NewMethodInfo(
		processPaymentHandler,
		newProcessPaymentArgs,
		newProcessPaymentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CancelPayment": kitex.NewMethodInfo(
		cancelPaymentHandler,
		newCancelPaymentArgs,
		newCancelPaymentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"HandlePaymentTimeout": kitex.NewMethodInfo(
		handlePaymentTimeoutHandler,
		newHandlePaymentTimeoutArgs,
		newHandlePaymentTimeoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetOrderByID": kitex.NewMethodInfo(
		getOrderByIDHandler,
		newGetOrderByIDArgs,
		newGetOrderByIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateOrderStatus": kitex.NewMethodInfo(
		updateOrderStatusHandler,
		newUpdateOrderStatusArgs,
		newUpdateOrderStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteOrder": kitex.NewMethodInfo(
		deleteOrderHandler,
		newDeleteOrderArgs,
		newDeleteOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateOrder": kitex.NewMethodInfo(
		createOrderHandler,
		newCreateOrderArgs,
		newCreateOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	paymentServiceServiceInfo                = NewServiceInfo()
	paymentServiceServiceInfoForClient       = NewServiceInfoForClient()
	paymentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return paymentServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PaymentService"
	handlerType := (*payment.PaymentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "rpc.payment",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func processPaymentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(payment.PaymentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(payment.PaymentService).ProcessPayment(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ProcessPaymentArgs:
		success, err := handler.(payment.PaymentService).ProcessPayment(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ProcessPaymentResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newProcessPaymentArgs() interface{} {
	return &ProcessPaymentArgs{}
}

func newProcessPaymentResult() interface{} {
	return &ProcessPaymentResult{}
}

type ProcessPaymentArgs struct {
	Req *payment.PaymentRequest
}

func (p *ProcessPaymentArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(payment.PaymentRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ProcessPaymentArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ProcessPaymentArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ProcessPaymentArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ProcessPaymentArgs) Unmarshal(in []byte) error {
	msg := new(payment.PaymentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ProcessPaymentArgs_Req_DEFAULT *payment.PaymentRequest

func (p *ProcessPaymentArgs) GetReq() *payment.PaymentRequest {
	if !p.IsSetReq() {
		return ProcessPaymentArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ProcessPaymentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProcessPaymentArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ProcessPaymentResult struct {
	Success *payment.PaymentResponse
}

var ProcessPaymentResult_Success_DEFAULT *payment.PaymentResponse

func (p *ProcessPaymentResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(payment.PaymentResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ProcessPaymentResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ProcessPaymentResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ProcessPaymentResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ProcessPaymentResult) Unmarshal(in []byte) error {
	msg := new(payment.PaymentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ProcessPaymentResult) GetSuccess() *payment.PaymentResponse {
	if !p.IsSetSuccess() {
		return ProcessPaymentResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ProcessPaymentResult) SetSuccess(x interface{}) {
	p.Success = x.(*payment.PaymentResponse)
}

func (p *ProcessPaymentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProcessPaymentResult) GetResult() interface{} {
	return p.Success
}

func cancelPaymentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(payment.CancelRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(payment.PaymentService).CancelPayment(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CancelPaymentArgs:
		success, err := handler.(payment.PaymentService).CancelPayment(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CancelPaymentResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCancelPaymentArgs() interface{} {
	return &CancelPaymentArgs{}
}

func newCancelPaymentResult() interface{} {
	return &CancelPaymentResult{}
}

type CancelPaymentArgs struct {
	Req *payment.CancelRequest
}

func (p *CancelPaymentArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(payment.CancelRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CancelPaymentArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CancelPaymentArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CancelPaymentArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CancelPaymentArgs) Unmarshal(in []byte) error {
	msg := new(payment.CancelRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CancelPaymentArgs_Req_DEFAULT *payment.CancelRequest

func (p *CancelPaymentArgs) GetReq() *payment.CancelRequest {
	if !p.IsSetReq() {
		return CancelPaymentArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CancelPaymentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CancelPaymentArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CancelPaymentResult struct {
	Success *payment.PaymentResponse
}

var CancelPaymentResult_Success_DEFAULT *payment.PaymentResponse

func (p *CancelPaymentResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(payment.PaymentResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CancelPaymentResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CancelPaymentResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CancelPaymentResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CancelPaymentResult) Unmarshal(in []byte) error {
	msg := new(payment.PaymentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CancelPaymentResult) GetSuccess() *payment.PaymentResponse {
	if !p.IsSetSuccess() {
		return CancelPaymentResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CancelPaymentResult) SetSuccess(x interface{}) {
	p.Success = x.(*payment.PaymentResponse)
}

func (p *CancelPaymentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CancelPaymentResult) GetResult() interface{} {
	return p.Success
}

func handlePaymentTimeoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(payment.PaymentTimeoutRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(payment.PaymentService).HandlePaymentTimeout(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *HandlePaymentTimeoutArgs:
		success, err := handler.(payment.PaymentService).HandlePaymentTimeout(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*HandlePaymentTimeoutResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newHandlePaymentTimeoutArgs() interface{} {
	return &HandlePaymentTimeoutArgs{}
}

func newHandlePaymentTimeoutResult() interface{} {
	return &HandlePaymentTimeoutResult{}
}

type HandlePaymentTimeoutArgs struct {
	Req *payment.PaymentTimeoutRequest
}

func (p *HandlePaymentTimeoutArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(payment.PaymentTimeoutRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *HandlePaymentTimeoutArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *HandlePaymentTimeoutArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *HandlePaymentTimeoutArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *HandlePaymentTimeoutArgs) Unmarshal(in []byte) error {
	msg := new(payment.PaymentTimeoutRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var HandlePaymentTimeoutArgs_Req_DEFAULT *payment.PaymentTimeoutRequest

func (p *HandlePaymentTimeoutArgs) GetReq() *payment.PaymentTimeoutRequest {
	if !p.IsSetReq() {
		return HandlePaymentTimeoutArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *HandlePaymentTimeoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *HandlePaymentTimeoutArgs) GetFirstArgument() interface{} {
	return p.Req
}

type HandlePaymentTimeoutResult struct {
	Success *payment.PaymentResponse
}

var HandlePaymentTimeoutResult_Success_DEFAULT *payment.PaymentResponse

func (p *HandlePaymentTimeoutResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(payment.PaymentResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *HandlePaymentTimeoutResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *HandlePaymentTimeoutResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *HandlePaymentTimeoutResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *HandlePaymentTimeoutResult) Unmarshal(in []byte) error {
	msg := new(payment.PaymentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *HandlePaymentTimeoutResult) GetSuccess() *payment.PaymentResponse {
	if !p.IsSetSuccess() {
		return HandlePaymentTimeoutResult_Success_DEFAULT
	}
	return p.Success
}

func (p *HandlePaymentTimeoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*payment.PaymentResponse)
}

func (p *HandlePaymentTimeoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HandlePaymentTimeoutResult) GetResult() interface{} {
	return p.Success
}

func getOrderByIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(payment.OrderRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(payment.PaymentService).GetOrderByID(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetOrderByIDArgs:
		success, err := handler.(payment.PaymentService).GetOrderByID(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetOrderByIDResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetOrderByIDArgs() interface{} {
	return &GetOrderByIDArgs{}
}

func newGetOrderByIDResult() interface{} {
	return &GetOrderByIDResult{}
}

type GetOrderByIDArgs struct {
	Req *payment.OrderRequest
}

func (p *GetOrderByIDArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(payment.OrderRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetOrderByIDArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetOrderByIDArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetOrderByIDArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetOrderByIDArgs) Unmarshal(in []byte) error {
	msg := new(payment.OrderRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetOrderByIDArgs_Req_DEFAULT *payment.OrderRequest

func (p *GetOrderByIDArgs) GetReq() *payment.OrderRequest {
	if !p.IsSetReq() {
		return GetOrderByIDArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetOrderByIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetOrderByIDArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetOrderByIDResult struct {
	Success *payment.OrderResponse
}

var GetOrderByIDResult_Success_DEFAULT *payment.OrderResponse

func (p *GetOrderByIDResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(payment.OrderResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetOrderByIDResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetOrderByIDResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetOrderByIDResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetOrderByIDResult) Unmarshal(in []byte) error {
	msg := new(payment.OrderResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetOrderByIDResult) GetSuccess() *payment.OrderResponse {
	if !p.IsSetSuccess() {
		return GetOrderByIDResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetOrderByIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*payment.OrderResponse)
}

func (p *GetOrderByIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetOrderByIDResult) GetResult() interface{} {
	return p.Success
}

func updateOrderStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(payment.UpdateStatusRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(payment.PaymentService).UpdateOrderStatus(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateOrderStatusArgs:
		success, err := handler.(payment.PaymentService).UpdateOrderStatus(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateOrderStatusResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateOrderStatusArgs() interface{} {
	return &UpdateOrderStatusArgs{}
}

func newUpdateOrderStatusResult() interface{} {
	return &UpdateOrderStatusResult{}
}

type UpdateOrderStatusArgs struct {
	Req *payment.UpdateStatusRequest
}

func (p *UpdateOrderStatusArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(payment.UpdateStatusRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UpdateOrderStatusArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UpdateOrderStatusArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UpdateOrderStatusArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateOrderStatusArgs) Unmarshal(in []byte) error {
	msg := new(payment.UpdateStatusRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateOrderStatusArgs_Req_DEFAULT *payment.UpdateStatusRequest

func (p *UpdateOrderStatusArgs) GetReq() *payment.UpdateStatusRequest {
	if !p.IsSetReq() {
		return UpdateOrderStatusArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateOrderStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateOrderStatusArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateOrderStatusResult struct {
	Success *payment.PaymentResponse
}

var UpdateOrderStatusResult_Success_DEFAULT *payment.PaymentResponse

func (p *UpdateOrderStatusResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(payment.PaymentResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UpdateOrderStatusResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UpdateOrderStatusResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UpdateOrderStatusResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateOrderStatusResult) Unmarshal(in []byte) error {
	msg := new(payment.PaymentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateOrderStatusResult) GetSuccess() *payment.PaymentResponse {
	if !p.IsSetSuccess() {
		return UpdateOrderStatusResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateOrderStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*payment.PaymentResponse)
}

func (p *UpdateOrderStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateOrderStatusResult) GetResult() interface{} {
	return p.Success
}

func deleteOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(payment.DeleteOrderRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(payment.PaymentService).DeleteOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteOrderArgs:
		success, err := handler.(payment.PaymentService).DeleteOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteOrderArgs() interface{} {
	return &DeleteOrderArgs{}
}

func newDeleteOrderResult() interface{} {
	return &DeleteOrderResult{}
}

type DeleteOrderArgs struct {
	Req *payment.DeleteOrderRequest
}

func (p *DeleteOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(payment.DeleteOrderRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteOrderArgs) Unmarshal(in []byte) error {
	msg := new(payment.DeleteOrderRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteOrderArgs_Req_DEFAULT *payment.DeleteOrderRequest

func (p *DeleteOrderArgs) GetReq() *payment.DeleteOrderRequest {
	if !p.IsSetReq() {
		return DeleteOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteOrderResult struct {
	Success *payment.PaymentResponse
}

var DeleteOrderResult_Success_DEFAULT *payment.PaymentResponse

func (p *DeleteOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(payment.PaymentResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteOrderResult) Unmarshal(in []byte) error {
	msg := new(payment.PaymentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteOrderResult) GetSuccess() *payment.PaymentResponse {
	if !p.IsSetSuccess() {
		return DeleteOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*payment.PaymentResponse)
}

func (p *DeleteOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteOrderResult) GetResult() interface{} {
	return p.Success
}

func createOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(payment.CreateOrderRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(payment.PaymentService).CreateOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateOrderArgs:
		success, err := handler.(payment.PaymentService).CreateOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateOrderArgs() interface{} {
	return &CreateOrderArgs{}
}

func newCreateOrderResult() interface{} {
	return &CreateOrderResult{}
}

type CreateOrderArgs struct {
	Req *payment.CreateOrderRequest
}

func (p *CreateOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(payment.CreateOrderRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CreateOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CreateOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CreateOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateOrderArgs) Unmarshal(in []byte) error {
	msg := new(payment.CreateOrderRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateOrderArgs_Req_DEFAULT *payment.CreateOrderRequest

func (p *CreateOrderArgs) GetReq() *payment.CreateOrderRequest {
	if !p.IsSetReq() {
		return CreateOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateOrderResult struct {
	Success *payment.OrderResponse
}

var CreateOrderResult_Success_DEFAULT *payment.OrderResponse

func (p *CreateOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(payment.OrderResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CreateOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CreateOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CreateOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateOrderResult) Unmarshal(in []byte) error {
	msg := new(payment.OrderResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateOrderResult) GetSuccess() *payment.OrderResponse {
	if !p.IsSetSuccess() {
		return CreateOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*payment.OrderResponse)
}

func (p *CreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateOrderResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ProcessPayment(ctx context.Context, Req *payment.PaymentRequest) (r *payment.PaymentResponse, err error) {
	var _args ProcessPaymentArgs
	_args.Req = Req
	var _result ProcessPaymentResult
	if err = p.c.Call(ctx, "ProcessPayment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelPayment(ctx context.Context, Req *payment.CancelRequest) (r *payment.PaymentResponse, err error) {
	var _args CancelPaymentArgs
	_args.Req = Req
	var _result CancelPaymentResult
	if err = p.c.Call(ctx, "CancelPayment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HandlePaymentTimeout(ctx context.Context, Req *payment.PaymentTimeoutRequest) (r *payment.PaymentResponse, err error) {
	var _args HandlePaymentTimeoutArgs
	_args.Req = Req
	var _result HandlePaymentTimeoutResult
	if err = p.c.Call(ctx, "HandlePaymentTimeout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOrderByID(ctx context.Context, Req *payment.OrderRequest) (r *payment.OrderResponse, err error) {
	var _args GetOrderByIDArgs
	_args.Req = Req
	var _result GetOrderByIDResult
	if err = p.c.Call(ctx, "GetOrderByID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateOrderStatus(ctx context.Context, Req *payment.UpdateStatusRequest) (r *payment.PaymentResponse, err error) {
	var _args UpdateOrderStatusArgs
	_args.Req = Req
	var _result UpdateOrderStatusResult
	if err = p.c.Call(ctx, "UpdateOrderStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteOrder(ctx context.Context, Req *payment.DeleteOrderRequest) (r *payment.PaymentResponse, err error) {
	var _args DeleteOrderArgs
	_args.Req = Req
	var _result DeleteOrderResult
	if err = p.c.Call(ctx, "DeleteOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateOrder(ctx context.Context, Req *payment.CreateOrderRequest) (r *payment.OrderResponse, err error) {
	var _args CreateOrderArgs
	_args.Req = Req
	var _result CreateOrderResult
	if err = p.c.Call(ctx, "CreateOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
