// Code generated by Kitex v0.12.1. DO NOT EDIT.

package paymentservice

import (
	paymentservice2 "TikTok-E-commerce-payment/kitex_gen/paymentservice"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ProcessPayment(ctx context.Context, Req *ProcessPaymentRequest, callOptions ...callopt.Option) (r *ProcessPaymentResponse, err error)
	CancelPayment(ctx context.Context, Req *CancelPaymentRequest, callOptions ...callopt.Option) (r *CancelPaymentResponse, err error)
	HandlePaymentTimeout(ctx context.Context, Req *PaymentTimeoutRequest, callOptions ...callopt.Option) (r *PaymentTimeoutResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(paymentservice2.serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPaymentServiceClient{
		kClient: paymentservice2.newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPaymentServiceClient struct {
	*paymentservice2.kClient
}

func (p *kPaymentServiceClient) ProcessPayment(ctx context.Context, Req *ProcessPaymentRequest, callOptions ...callopt.Option) (r *ProcessPaymentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ProcessPayment(ctx, Req)
}

func (p *kPaymentServiceClient) CancelPayment(ctx context.Context, Req *CancelPaymentRequest, callOptions ...callopt.Option) (r *CancelPaymentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelPayment(ctx, Req)
}

func (p *kPaymentServiceClient) HandlePaymentTimeout(ctx context.Context, Req *PaymentTimeoutRequest, callOptions ...callopt.Option) (r *PaymentTimeoutResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HandlePaymentTimeout(ctx, Req)
}
