// Code generated by Kitex v0.12.1. DO NOT EDIT.
package paymentservice

import (
	paymentservice2 "TikTok-E-commerce-payment/kitex_gen/paymentservice"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler PaymentService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(paymentservice2.serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler PaymentService, opts ...server.RegisterOption) error {
	return svr.RegisterService(paymentservice2.serviceInfo(), handler, opts...)
}
